version: '3'
services:
  app:
    build: 
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/myapp 
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    networks: 
      - PFC-balance-app-network  
  web:
    build: 
      context: containers/nginx
    volumes: 
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80        
    depends_on: 
      - app
    networks: 
      - PFC-balance-app-network
volumes:
  public-data:
  tmp-data:
  log-data:
  mysql-db:

networks: 
  PFC-balance-app-network:
    external: true
  