version: '3'
services:
  # =========ローカルと本番切り替え===========
  #db:
  #  image: mysql:8.0.23 
  #  command: --default-authentication-plugin=mysql_native_password
  #  environment:
  #    MYSQL_DATABASE: PFC_balance_app_development
  #    MYSQL_ROOT_PASSWORD: password
  #    MYSQL_USER: root
  #    MYSQL_PASSWORD: password
  #  volumes:
  #    - ./mysql-db/data:/var/lib/mysql
  #
  #test-db:
  #  image: mysql:8.0.23
  #  command: --default-authentication-plugin=mysql_native_password
  #  environment: 
  #    MYSQL_DATABASE: PFC_balance_app_test
  #    MYSQL_ROOT_PASSWORD: password
  #    MYSQL_USER: test-root
  #    MYSQL_PASSWORD: password
  # ======================================
  app:
    build: 
      context: .
  # =========ローカルと本番切り替え=========== 
    command: bundle exec puma -C config/puma.rb -e production
    #command: bundle exec puma -C config/puma.rb
    #depends_on:
    #  - db
    #  - chrome
  # ======================================      
    volumes:
      - .:/myapp 
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
  # =========ローカルと本番切り替え===========     
  #chrome:
  #  image: selenium/standalone-chrome-debug:latest
  #  ports:
  #    - 5900:5900
  # ======================================  
  web:
    build: 
      context: containers/nginx
    volumes: 
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
  # =========ローカルと本番切り替え===========         
    #depends_on: 
    #  - app
  # ======================================    
volumes:
  public-data:
  tmp-data:
  log-data:
  mysql-db:

  