default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 

development:
  <<: *default
  database: PFC_balance_app_development
  username: root
  password: password
  host: db

test:
  <<: *default
  database: PFC_balance_app_test
  username: test-root
  password: password
  host: test-db

production:
  <<: *default
  database: PFC_balance_app_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>